version: '3'

services:
  db:
    image: postgres:9.4
    restart: always
    volumes:
      - /disco_duro/odoo-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata

  app:  
    image: odoo:11.0
    restart: always
    volumes:
      - /disco_duro/odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - VIRTUAL_HOST=dattechs.pruebaclouds.com
      - LETSENCRYPT_HOST=dattechs.pruebaclouds.com
      - LETSENCRYPT_EMAIL=andrescarlos88carpio@gmail.com
    depends_on:
      - db
     ports:
      - 8069:8069
    networks:
      - proxy-odoo
      - default

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-odoo

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-odoo
    depends_on:
      - proxy

volumes:
  db:
  odoo-web-data:
  odoo-db-data
  certs:
  vhost.d:
  html:

networks:
  proxy-odoo:
