version: '3'

services:
  db:
    image: postgres:9.4
    restart: always
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  web:
    build: ./odoo
    restart: always
    depends_on:
      - db
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - VIRTUAL_HOST=odoo.pruebaclouds.com
      - LETSENCRYPT_HOST=odoo.pruebaclouds.com
      - LETSENCRYPT_EMAIL=andrescarlos88carpio@gmail.com
      - MYSQL_HOST=db
    networks:
      - odoo-tier
      - default
  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - odoo-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - odoo-tier
    depends_on:
      - proxy
volumes:
  odoo-web-data:
  odoo-db-data:
  certs:
  vhost.d:
  html:

networks:
  odoo-tier:
